export const Technologies = [
  {
    name: "React.js",
    logo: "Logos/reaCT.svg",
    describtion: "opis",
  },
  { name: "Type Script", logo: "Logos/ts.svg", describtion: "opis" },
  { name: "Java Script", logo: "Logos/js.svg", describtion: "opis" },
  { name: "CSS", logo: "Logos/css.svg", describtion: "opis" },
  { name: "HTML", logo: "Logos/html.svg", describtion: "opis" },
  { name: "Node Package Manager", logo: "Logos/npm.svg", describtion: "opis" },
  { name: "GIT", logo: "Logos/git.svg", describtion: "opis" },
  { name: "Redux", logo: "Logos/redux.svg", describtion: "opis" },
  { name: "SASS", logo: "Logos/sass.svg", describtion: "opis" },
  { name: "Visual Studio Code", logo: "Logos/vs.svg", describtion: "opis" },
  { name: "Webpack", logo: "Logos/webpack.svg", describtion: "opis" },
  { name: "GIMP", logo: "Logos/gimp.svg", describtion: "opis" },
  { name: "Figma", logo: "Logos/figma.svg", describtion: "opis" },
  { name: "Chakra UI", logo: "Logos/chakra.svg", describtion: "opis" },
  { name: "React Router", logo: "Logos/router.svg", describtion: "opis" },
];
